### PR TITLE
Update shorturl-services-list.txt

### PR DESCRIPTION
**Pull request by Carcraftz**

### CODE REVIEW

**Comment by sambokai** [comment]
Thank you for your PR @Carcraftz. `niny.io` does not seem to be online.

**Comment by Carcraftz** [comment]
Currently our domain service is down, you caught us at a bad time! 🙃

**Comment by Carcraftz** [comment]
Our service is fixed, you can check now :)

**Comment by sambokai** [comment]
Confirmed that it is up and working

**Comment by sambokai** [comment]
@Carcraftz Please sort the file and I'll merge

**Comment by sambokai** [comment]
I went ahead and sorted

**Pull request merged**
